import React from "react";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import './globals.css'
import { Inter } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" className={inter.className}>
      <ClerkProvider>
      <body className="h-full antialised mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">{children}</body>
      </ClerkProvider>

    </html>

  )
}
